# Generated by Django 3.0 on 2019-12-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=50)),
                ('bathrooms', models.FloatField()),
                ('bedrooms', models.FloatField()),
                ('home_size', models.FloatField()),
                ('home_type', models.FloatField()),
                ('last_sold_date', models.DateField()),
                ('last_sold_price', models.FloatField()),
                ('link', models.TextField()),
                ('price', models.FloatField()),
                ('property_size', models.FloatField()),
                ('rent_price', models.FloatField()),
                ('rentzestimate_amount', models.FloatField()),
                ('rentzestimate_last_updated', models.DateField()),
                ('tax_value', models.FloatField()),
                ('tax_year', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('zestimate_amount', models.FloatField()),
                ('zillow_id', models.BigIntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
            ],
        ),
    ]
