# Generated by Django 3.0 on 2019-12-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='zestimate_last_updated',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='last_sold_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='rentzestimate_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='rentzestimate_last_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='tax_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='tax_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='year_built',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='zestimate_amount',
            field=models.FloatField(null=True),
        ),
    ]
