# Generated by Django 3.0 on 2019-12-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow', '0002_auto_20191206_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='home_type',
            field=models.CharField(max_length=20),
        ),
    ]
