# Generated by Django 3.0 on 2019-12-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow', '0003_auto_20191206_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='last_sold_price',
            field=models.FloatField(null=True),
        ),
    ]
