# Generated by Django 3.0 on 2019-12-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow', '0004_auto_20191206_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='last_sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='last_sold_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='rentzestimate_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='rentzestimate_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='tax_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='tax_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='zestimate_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
