# Generated by Django 3.0 on 2019-12-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow', '0005_auto_20191206_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='bathrooms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='bedrooms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='home_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='property_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='rent_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
